### ISSUE TITLE
Please can you help me fix this?

### ISSUE THREAD

**Issue by PenguThePenguin** [styxit/MinecraftStatusPage#1]
I downloaded the files, ran composer and then uploaded it to my website.
![image](https://user-images.githubusercontent.com/57046639/87295796-a27b9700-c4fd-11ea-983e-1fa26c4a36ed.png)
But when I go to the website, this shows up.
![image](https://user-images.githubusercontent.com/57046639/87296088-26ce1a00-c4fe-11ea-90a8-10a8563fa8bd.png)
Please can you tell me how to fix this?
-Thanks

**Comment by PenguThePenguin** [comment]
I was able to fix this by renaming the folder to public_html.
Thanks for this awsome website!

**Comment by PenguThePenguin** [comment]
Where do I go to change the IP it queries?

**Comment by styxit** [comment]
Looks like you initially did not point your webroot to the `public` folder, but i see you've found the solution.

In the `.env` file you can specify the host/IP for the server you want to get stats for.

**Comment by PenguThePenguin** [comment]
I use the ip 79.137.123.244 but it says its offline

**Comment by styxit** [comment]
@Mitzythecat If your minecraft server is running on a non-default port (default is 25565) you might need to specify the port in the .env

This seems to work.
```
SERVER_HOST=79.137.123.244:25585
```
